In [52]:
from sklearn import preprocessing, metrics
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn import preprocessing, linear_model, model_selection
import matplotlib.pyplot as plt
import seaborn as sns


import statsmodels.api as sm

In [23]:
def load_csv(file_name):
    df = pd.read_csv(file_name)
    return df

In [24]:
df = load_csv('./FinalData.csv')
df = df.drop(columns=["Unnamed: 0"])

In [25]:
df

apartment_type  rooms    price  window_bars  partners  furniture  \
0            דירת גג    4.0   8800.0            0         0        0.0   
1               דירה    2.5   3200.0            0         0        0.0   
2               דירה    3.5   3500.0            0         0        0.0   
3               דירה    3.0   5500.0            0         0        0.0   
4               דירה    4.0  10000.0            0         0        0.0   
...              ...    ...      ...          ...       ...        ...   
48386           דירה    3.5   8700.0            0         0        1.0   
48387           דירה    3.0   6200.0            0         0        1.0   
48388           דירה    3.0   6200.0            0         0        1.0   
48389           דירה    2.0   4200.0            0         0        0.0   
48390           דירה    2.0   5500.0            0         0        0.0   

       elevator  balcony  air_conditioner  parking  floor  max_floor  \
0             1        1                1        1    5.0        6.0   
1             0        1                1        1    2.0        4.0   
2             0        0                1        0    1.0        4.0   
3             0        1                1        0    1.0        3.0   
4             1        0                1        1    1.0        6.0   
...         ...      ...              ...      ...    ...        ...   
48386         1        0                1        1   10.0       15.0   
48387         0        1                1        0    3.0        3.0   
48388         0        1                1        0    3.0        3.0   
48389         0        0                1        1    3.0        4.0   
48390         0        1                1        0    2.0        2.0   

       size_in_meters  
0               100.0  
1                50.0  
2                80.0  
3                90.0  
4               140.0  
...               ...  
48386           110.0  
48387            60.0  
48388            60.0  
48389            65.0  
48390            65.0  

[48391 rows x 13 columns]

In [ ]:
df['price'] = df['price'].astype('int')

In [72]:
copy_df=df.drop(["apartment_type"],axis=1).copy()

In [73]:
copy_df

rooms  price  window_bars  partners  furniture  elevator  balcony  \
0        4.0   8800            0         0        0.0         1        1   
1        2.5   3200            0         0        0.0         0        1   
2        3.5   3500            0         0        0.0         0        0   
3        3.0   5500            0         0        0.0         0        1   
4        4.0  10000            0         0        0.0         1        0   
...      ...    ...          ...       ...        ...       ...      ...   
48386    3.5   8700            0         0        1.0         1        0   
48387    3.0   6200            0         0        1.0         0        1   
48388    3.0   6200            0         0        1.0         0        1   
48389    2.0   4200            0         0        0.0         0        0   
48390    2.0   5500            0         0        0.0         0        1   

       air_conditioner  parking  floor  max_floor  size_in_meters  
0                    1        1    5.0        6.0           100.0  
1                    1        1    2.0        4.0            50.0  
2                    1        0    1.0        4.0            80.0  
3                    1        0    1.0        3.0            90.0  
4                    1        1    1.0        6.0           140.0  
...                ...      ...    ...        ...             ...  
48386                1        1   10.0       15.0           110.0  
48387                1        0    3.0        3.0            60.0  
48388                1        0    3.0        3.0            60.0  
48389                1        1    3.0        4.0            65.0  
48390                1        0    2.0        2.0            65.0  

[48391 rows x 12 columns]

In [74]:
copy_df.describe()

rooms         price   window_bars      partners     furniture  \
count  48391.000000  48391.000000  48391.000000  48391.000000  48391.000000   
mean       3.196286   5979.730239      0.297741      0.264016      0.262673   
std        0.966459   2267.426410      0.457270      0.440812      0.440091   
min        1.500000   1100.000000      0.000000      0.000000      0.000000   
25%        2.500000   4500.000000      0.000000      0.000000      0.000000   
50%        3.000000   5700.000000      0.000000      0.000000      0.000000   
75%        4.000000   7000.000000      1.000000      1.000000      1.000000   
max        6.000000  14900.000000      1.000000      1.000000      1.000000   

           elevator       balcony  air_conditioner       parking  \
count  48391.000000  48391.000000     48391.000000  48391.000000   
mean       0.478705      0.620095         0.936145      0.546155   
std        0.499551      0.485368         0.244497      0.497870   
min        0.000000      0.000000         0.000000      0.000000   
25%        0.000000      0.000000         1.000000      0.000000   
50%        0.000000      1.000000         1.000000      1.000000   
75%        1.000000      1.000000         1.000000      1.000000   
max        1.000000      1.000000         1.000000      1.000000   

              floor     max_floor  size_in_meters  
count  48391.000000  48391.000000    48391.000000  
mean       2.726829      4.869170       89.362319  
std        3.152991      4.117666       40.901270  
min       -1.000000     -1.000000        2.000000  
25%        1.000000      3.000000       65.000000  
50%        2.000000      4.000000       80.000000  
75%        3.000000      5.000000      108.000000  
max       50.000000     50.000000     1500.000000

In [75]:
TRAINING_FEATURES = copy_df.columns[copy_df.columns != 'price']
TARGET_FEATURE = 'price'

X = copy_df[TRAINING_FEATURES]
y = copy_df[TARGET_FEATURE]

In [76]:
X.head()

rooms  window_bars  partners  furniture  elevator  balcony  \
0    4.0            0         0        0.0         1        1   
1    2.5            0         0        0.0         0        1   
2    3.5            0         0        0.0         0        0   
3    3.0            0         0        0.0         0        1   
4    4.0            0         0        0.0         1        0   

   air_conditioner  parking  floor  max_floor  size_in_meters  
0                1        1    5.0        6.0           100.0  
1                1        1    2.0        4.0            50.0  
2                1        0    1.0        4.0            80.0  
3                1        0    1.0        3.0            90.0  
4                1        1    1.0        6.0           140.0

In [77]:
y.head()

0     8800
1     3200
2     3500
3     5500
4    10000
Name: price, dtype: int32

In [78]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2)

In [79]:
X_train

rooms  window_bars  partners  furniture  elevator  balcony  \
42238    4.0            1         0        0.0         1        1   
35767    5.0            0         0        0.0         0        1   
39032    2.0            0         0        0.0         0        0   
21669    4.0            0         0        0.0         1        1   
16732    2.5            0         0        1.0         0        1   
...      ...          ...       ...        ...       ...      ...   
30575    5.0            0         0        0.0         1        0   
30455    3.5            0         1        0.0         0        0   
27338    3.0            0         0        0.0         0        0   
9491     2.5            0         0        1.0         0        1   
9543     2.5            0         0        1.0         0        1   

       air_conditioner  parking  floor  max_floor  size_in_meters  
42238                1        1    6.0        8.0            90.0  
35767                1        1    2.0        2.0           260.0  
39032                1        0    1.0        4.0            64.0  
21669                1        0    3.0        4.0           110.0  
16732                1        1    3.0        3.0            65.0  
...                ...      ...    ...        ...             ...  
30575                1        1    2.0        4.0           140.0  
30455                1        1    3.0        4.0            70.0  
27338                1        0    4.0        4.0            75.0  
9491                 1        0    2.0        4.0            75.0  
9543                 1        1    2.0        4.0            70.0  

[38712 rows x 11 columns]

In [80]:
X_test

rooms  window_bars  partners  furniture  elevator  balcony  \
38362    4.0            0         0        0.0         1        1   
43008    2.5            0         1        0.0         0        1   
11172    4.0            1         1        0.0         1        1   
20955    3.0            0         1        0.0         1        1   
15267    4.0            0         1        0.0         0        0   
...      ...          ...       ...        ...       ...      ...   
43096    3.0            1         1        0.0         0        1   
35240    3.0            0         0        1.0         0        0   
17421    2.5            0         0        1.0         1        1   
23349    3.0            1         1        0.0         0        1   
23872    4.0            0         0        0.0         0        0   

       air_conditioner  parking  floor  max_floor  size_in_meters  
38362                1        1   12.0       31.0           120.0  
43008                0        1    3.0        3.0            80.0  
11172                1        1    1.0        4.0           110.0  
20955                1        1    2.0        4.0            85.0  
15267                0        1    0.0        3.0           125.0  
...                ...      ...    ...        ...             ...  
43096                1        0    2.0        4.0            75.0  
35240                1        0    1.0        3.0            80.0  
17421                1        0    0.0        3.0            58.0  
23349                1        0    2.0        4.0            85.0  
23872                1        1    2.0        2.0           110.0  

[9679 rows x 11 columns]

In [81]:
y_test

38362    10000
43008     2500
11172     7800
20955     6500
15267     6500
         ...  
43096     7500
35240     7500
17421     5200
23349     5500
23872     4100
Name: price, Length: 9679, dtype: int32

In [82]:
y_train

42238    5500
35767    9000
39032    6000
21669    7200
16732    5500
         ... 
30575    5200
30455    4500
27338    7000
9491     4800
9543     3700
Name: price, Length: 38712, dtype: int32

In [83]:
reg = LinearRegression(fit_intercept=False)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)

In [84]:
reg = LinearRegression(fit_intercept=False)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)

In [85]:
reg.coef_

array([ 752.60368208,  -37.1829671 ,  136.49088693,  256.11531057,
        936.32173559,  380.13589428, 1628.0670649 , -508.78455808,
         32.4995022 ,   23.38020977,   14.51468764])

In [103]:
for key,val in sorted(dict(zip(copy_df.columns,reg.coef_)).items(),key=lambda x:x[1],reverse=True):
    print(key,val)

balcony 1628.0670649008907
furniture 936.3217355948773
rooms 752.6036820761436
elevator 380.13589428457175
partners 256.11531056571664
window_bars 136.4908869295087
parking 32.49950219856522
floor 23.380209768051643
max_floor 14.514687643525384
price -37.182967104981884
air_conditioner -508.78455807685765


In [104]:
y_pred = reg.predict(X)
pred_df = pd.DataFrame({'Actual': y, 'Predicted': y_pred})
pred_df["Difference"] = pred_df["Actual"] - pred_df["Predicted"]

In [105]:
pred_df

Actual    Predicted   Difference
0        8800  7200.402399  1599.597601
1        3200  4265.181832 -1065.181832
2        3500  5549.375305 -2049.375305
3        5500  5674.976025  -174.976025
4       10000  7270.856002  2729.143998
...       ...          ...          ...
48386    8700  7218.146250  1481.853750
48387    6200  5560.649710   639.350290
48388    6200  5560.649710   639.350290
48389    4200  3758.963913   441.036087
48390    5500  4568.624444   931.375556

[48391 rows x 3 columns]

In [ ]:
#different approach

In [106]:
scale = StandardScaler()
X_train_scale = scale.fit_transform(X_train)

In [107]:
X_train_scale

array([[ 0.83440008,  1.52776953, -0.60066517, ...,  1.03996544,
         0.76452661,  0.01647819],
       [ 1.87114349, -0.65454899, -0.60066517, ..., -0.23068038,
        -0.69817746,  4.17252112],
       [-1.23908673, -0.65454899, -0.60066517, ..., -0.54834183,
        -0.21060944, -0.61915191],
       ...,
       [-0.20234333, -0.65454899, -0.60066517, ...,  0.40464253,
        -0.21060944, -0.35023148],
       [-0.72071503, -0.65454899, -0.60066517, ..., -0.23068038,
        -0.21060944, -0.35023148],
       [-0.72071503, -0.65454899, -0.60066517, ..., -0.23068038,
        -0.21060944, -0.47246804]])

In [108]:
scaled_X = scale.transform(X_test)
scaled_X

array([[ 0.83440008, -0.65454899, -0.60066517, ...,  2.94593416,
         6.3715589 ,  0.74989753],
       [-0.72071503, -0.65454899,  1.66482101, ...,  0.08698108,
        -0.45439345, -0.22799492],
       [ 0.83440008,  1.52776953,  1.66482101, ..., -0.54834183,
        -0.21060944,  0.50542442],
       ...,
       [-0.72071503, -0.65454899, -0.60066517, ..., -0.86600329,
        -0.45439345, -0.76583577],
       [-0.20234333,  1.52776953,  1.66482101, ..., -0.23068038,
        -0.21060944, -0.10575837],
       [ 0.83440008, -0.65454899, -0.60066517, ..., -0.23068038,
        -0.69817746,  0.50542442]])

In [109]:
classification_standard_model = LogisticRegression(max_iter = 50000).fit(X_train_scale, y_train)

In [110]:
classification_standard_model.coef_

array([[ 0.41118585,  0.76571364, -0.34090188, ...,  0.52113018,
        -0.14500886, -0.13970271],
       [-0.17630957, -0.65433175,  0.07609887, ...,  0.07123703,
        -0.62410506, -0.57817758],
       [ 0.57378343, -0.30481355, -0.22710225, ...,  0.03333914,
        -0.22424258,  0.20671628],
       ...,
       [ 0.83958684,  0.20247434, -0.48114806, ...,  0.24259844,
         0.57898924,  0.49624128],
       [-0.55952603, -0.20620851, -0.26402138, ...,  0.68089471,
        -0.00821459, -0.01021803],
       [-0.65222805, -0.4456967 ,  0.60711777, ...,  0.48191557,
         0.10267845,  0.73088507]])

In [111]:
df_pred2 = pd.DataFrame({"Actual": y_test , "Predicted": classification_standard_model.predict(X_test)})

In [112]:
df_pred2

Actual  Predicted
38362   10000      12000
43008    2500      11800
11172    7800      11800
20955    6500      11800
15267    6500      11800
...       ...        ...
43096    7500      12000
35240    7500      12000
17421    5200      12000
23349    5500      12000
23872    4100      11800

[9679 rows x 2 columns]